apiVersion: v1
kind: Service
metadata:
  name: validateorder
spec:
  ports:
  - port: 8090
    targetPort: 8091
    name: http
  - port: 8090
    targetPort: 8091
    name: management
  selector:
    app: validateorder
  type: LoadBalancer