//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.01 at 02:39:05 PM IST 
//


package com.hp.sales.om.orders;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Common contact information
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}ContactName" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}ContactID" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}ContactDivision" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}ContactPhone" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}ContactPhoneHome" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}ContactPhoneMobile" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}ContactFax" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}ContactEmail" minOccurs="0"/>
 *         &lt;element name="ContactEmail2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ContacType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ContactParty" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contactName",
    "contactID",
    "contactDivision",
    "contactPhone",
    "contactPhoneHome",
    "contactPhoneMobile",
    "contactFax",
    "contactEmail",
    "contactEmail2"
})
@XmlRootElement(name = "ContactInfo")
public class ContactInfo {

    @XmlElement(name = "ContactName")
    protected List<ContactName> contactName;
    @XmlElement(name = "ContactID")
    protected String contactID;
    @XmlElement(name = "ContactDivision")
    protected List<String> contactDivision;
    @XmlElement(name = "ContactPhone")
    protected String contactPhone;
    @XmlElement(name = "ContactPhoneHome")
    protected String contactPhoneHome;
    @XmlElement(name = "ContactPhoneMobile")
    protected String contactPhoneMobile;
    @XmlElement(name = "ContactFax")
    protected String contactFax;
    @XmlElement(name = "ContactEmail")
    protected String contactEmail;
    @XmlElement(name = "ContactEmail2")
    protected String contactEmail2;
    @XmlAttribute(name = "ContacType")
    protected String contacType;
    @XmlAttribute(name = "ContactParty")
    protected String contactParty;

    /**
     * Gets the value of the contactName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactName }
     * 
     * 
     */
    public List<ContactName> getContactName() {
        if (contactName == null) {
            contactName = new ArrayList<ContactName>();
        }
        return this.contactName;
    }

    /**
     * Gets the value of the contactID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactID() {
        return contactID;
    }

    /**
     * Sets the value of the contactID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactID(String value) {
        this.contactID = value;
    }

    /**
     * Gets the value of the contactDivision property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactDivision property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactDivision().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContactDivision() {
        if (contactDivision == null) {
            contactDivision = new ArrayList<String>();
        }
        return this.contactDivision;
    }

    /**
     * Gets the value of the contactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * Sets the value of the contactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhone(String value) {
        this.contactPhone = value;
    }

    /**
     * Gets the value of the contactPhoneHome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhoneHome() {
        return contactPhoneHome;
    }

    /**
     * Sets the value of the contactPhoneHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhoneHome(String value) {
        this.contactPhoneHome = value;
    }

    /**
     * Gets the value of the contactPhoneMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhoneMobile() {
        return contactPhoneMobile;
    }

    /**
     * Sets the value of the contactPhoneMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhoneMobile(String value) {
        this.contactPhoneMobile = value;
    }

    /**
     * Gets the value of the contactFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactFax() {
        return contactFax;
    }

    /**
     * Sets the value of the contactFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactFax(String value) {
        this.contactFax = value;
    }

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactEmail(String value) {
        this.contactEmail = value;
    }

    /**
     * Gets the value of the contactEmail2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactEmail2() {
        return contactEmail2;
    }

    /**
     * Sets the value of the contactEmail2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactEmail2(String value) {
        this.contactEmail2 = value;
    }

    /**
     * Gets the value of the contacType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContacType() {
        return contacType;
    }

    /**
     * Sets the value of the contacType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContacType(String value) {
        this.contacType = value;
    }

    /**
     * Gets the value of the contactParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactParty() {
        return contactParty;
    }

    /**
     * Sets the value of the contactParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactParty(String value) {
        this.contactParty = value;
    }

}
