//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.01 at 02:39:05 PM IST 
//


package com.hp.sales.om.orders;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserLogin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UserIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmployeeIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RequestorIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BuyerApproverIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BuyerApproverCompanyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BuyerApproverEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VendorApproverIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userLogin",
    "userIdentifier",
    "employeeIdentifier",
    "requestorIdentifier",
    "buyerApproverIdentifier",
    "buyerApproverCompanyName",
    "buyerApproverEmail",
    "vendorApproverIdentifier"
})
@XmlRootElement(name = "Identifier")
public class Identifier {

    @XmlElement(name = "UserLogin")
    protected String userLogin;
    @XmlElement(name = "UserIdentifier")
    protected String userIdentifier;
    @XmlElement(name = "EmployeeIdentifier")
    protected String employeeIdentifier;
    @XmlElement(name = "RequestorIdentifier")
    protected String requestorIdentifier;
    @XmlElement(name = "BuyerApproverIdentifier")
    protected String buyerApproverIdentifier;
    @XmlElement(name = "BuyerApproverCompanyName")
    protected String buyerApproverCompanyName;
    @XmlElement(name = "BuyerApproverEmail")
    protected String buyerApproverEmail;
    @XmlElement(name = "VendorApproverIdentifier")
    protected String vendorApproverIdentifier;

    /**
     * Gets the value of the userLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLogin() {
        return userLogin;
    }

    /**
     * Sets the value of the userLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLogin(String value) {
        this.userLogin = value;
    }

    /**
     * Gets the value of the userIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserIdentifier() {
        return userIdentifier;
    }

    /**
     * Sets the value of the userIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserIdentifier(String value) {
        this.userIdentifier = value;
    }

    /**
     * Gets the value of the employeeIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeIdentifier() {
        return employeeIdentifier;
    }

    /**
     * Sets the value of the employeeIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeIdentifier(String value) {
        this.employeeIdentifier = value;
    }

    /**
     * Gets the value of the requestorIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestorIdentifier() {
        return requestorIdentifier;
    }

    /**
     * Sets the value of the requestorIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestorIdentifier(String value) {
        this.requestorIdentifier = value;
    }

    /**
     * Gets the value of the buyerApproverIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerApproverIdentifier() {
        return buyerApproverIdentifier;
    }

    /**
     * Sets the value of the buyerApproverIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerApproverIdentifier(String value) {
        this.buyerApproverIdentifier = value;
    }

    /**
     * Gets the value of the buyerApproverCompanyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerApproverCompanyName() {
        return buyerApproverCompanyName;
    }

    /**
     * Sets the value of the buyerApproverCompanyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerApproverCompanyName(String value) {
        this.buyerApproverCompanyName = value;
    }

    /**
     * Gets the value of the buyerApproverEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerApproverEmail() {
        return buyerApproverEmail;
    }

    /**
     * Sets the value of the buyerApproverEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerApproverEmail(String value) {
        this.buyerApproverEmail = value;
    }

    /**
     * Gets the value of the vendorApproverIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorApproverIdentifier() {
        return vendorApproverIdentifier;
    }

    /**
     * Sets the value of the vendorApproverIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorApproverIdentifier(String value) {
        this.vendorApproverIdentifier = value;
    }

}
