//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.01 at 02:39:05 PM IST 
//


package com.hp.sales.om.orders;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Customer specific instructions
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}InstructCode" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}InstructCodesc" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}InstructValue" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="InstrucType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="showOnReport" default="1">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instructCode",
    "instructCodesc",
    "instructValue"
})
@XmlRootElement(name = "Instructions")
public class Instructions {

    @XmlElement(name = "InstructCode")
    protected String instructCode;
    @XmlElement(name = "InstructCodesc")
    protected String instructCodesc;
    @XmlElement(name = "InstructValue")
    protected String instructValue;
    @XmlAttribute(name = "InstrucType", required = true)
    protected String instrucType;
    @XmlAttribute(name = "showOnReport")
    protected Integer showOnReport;

    /**
     * Gets the value of the instructCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructCode() {
        return instructCode;
    }

    /**
     * Sets the value of the instructCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructCode(String value) {
        this.instructCode = value;
    }

    /**
     * Gets the value of the instructCodesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructCodesc() {
        return instructCodesc;
    }

    /**
     * Sets the value of the instructCodesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructCodesc(String value) {
        this.instructCodesc = value;
    }

    /**
     * Gets the value of the instructValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructValue() {
        return instructValue;
    }

    /**
     * Sets the value of the instructValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructValue(String value) {
        this.instructValue = value;
    }

    /**
     * Gets the value of the instrucType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrucType() {
        return instrucType;
    }

    /**
     * Sets the value of the instrucType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrucType(String value) {
        this.instrucType = value;
    }

    /**
     * Gets the value of the showOnReport property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getShowOnReport() {
        if (showOnReport == null) {
            return  1;
        } else {
            return showOnReport;
        }
    }

    /**
     * Sets the value of the showOnReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setShowOnReport(Integer value) {
        this.showOnReport = value;
    }

}
