//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.01 at 02:39:05 PM IST 
//


package com.hp.sales.om.orders;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Line Item
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://hp.com/sales/om/orders/}Item"/>
 *           &lt;element ref="{http://hp.com/sales/om/orders/}BundleItem"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}Transport" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item",
    "bundleItem",
    "transport"
})
@XmlRootElement(name = "OrderItem")
public class OrderItem {

    @XmlElement(name = "Item")
    protected Item item;
    @XmlElement(name = "BundleItem")
    protected BundleItem bundleItem;
    @XmlElement(name = "Transport")
    protected Transport transport;

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link Item }
     *     
     */
    public Item getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link Item }
     *     
     */
    public void setItem(Item value) {
        this.item = value;
    }

    /**
     * Gets the value of the bundleItem property.
     * 
     * @return
     *     possible object is
     *     {@link BundleItem }
     *     
     */
    public BundleItem getBundleItem() {
        return bundleItem;
    }

    /**
     * Sets the value of the bundleItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundleItem }
     *     
     */
    public void setBundleItem(BundleItem value) {
        this.bundleItem = value;
    }

    /**
     * Gets the value of the transport property.
     * 
     * @return
     *     possible object is
     *     {@link Transport }
     *     
     */
    public Transport getTransport() {
        return transport;
    }

    /**
     * Sets the value of the transport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transport }
     *     
     */
    public void setTransport(Transport value) {
        this.transport = value;
    }

}
