//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.01 at 02:39:05 PM IST 
//


package com.hp.sales.om.orders;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}CardType"/>
 *         &lt;element name="PGSID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AllocatedAmount" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="CardIssuerBank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}CardNum" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}CardAuthCode" minOccurs="0"/>
 *         &lt;element name="CardAuthInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardAuthDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}CardRefNum" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}CardExpirationDate" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}CardTypeOther" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}CardHolderName" minOccurs="0"/>
 *         &lt;element name="CardReportingLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardType",
    "pgsid",
    "allocatedAmount",
    "cardIssuerBank",
    "cardNum",
    "cardAuthCode",
    "cardAuthInfo",
    "cardAuthDate",
    "cardRefNum",
    "cardExpirationDate",
    "cardTypeOther",
    "cardHolderName",
    "cardReportingLevel"
})
@XmlRootElement(name = "CardInfo")
public class CardInfo {

    @XmlElement(name = "CardType", required = true)
    protected String cardType;
    @XmlElement(name = "PGSID")
    protected String pgsid;
    @XmlElement(name = "AllocatedAmount")
    protected Float allocatedAmount;
    @XmlElement(name = "CardIssuerBank")
    protected String cardIssuerBank;
    @XmlElement(name = "CardNum")
    protected String cardNum;
    @XmlElement(name = "CardAuthCode")
    protected String cardAuthCode;
    @XmlElement(name = "CardAuthInfo")
    protected String cardAuthInfo;
    @XmlElement(name = "CardAuthDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cardAuthDate;
    @XmlElement(name = "CardRefNum")
    protected String cardRefNum;
    @XmlElement(name = "CardExpirationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cardExpirationDate;
    @XmlElement(name = "CardTypeOther")
    protected String cardTypeOther;
    @XmlElement(name = "CardHolderName")
    protected String cardHolderName;
    @XmlElement(name = "CardReportingLevel")
    protected String cardReportingLevel;

    /**
     * Gets the value of the cardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * Sets the value of the cardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardType(String value) {
        this.cardType = value;
    }

    /**
     * Gets the value of the pgsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPGSID() {
        return pgsid;
    }

    /**
     * Sets the value of the pgsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPGSID(String value) {
        this.pgsid = value;
    }

    /**
     * Gets the value of the allocatedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAllocatedAmount() {
        return allocatedAmount;
    }

    /**
     * Sets the value of the allocatedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAllocatedAmount(Float value) {
        this.allocatedAmount = value;
    }

    /**
     * Gets the value of the cardIssuerBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardIssuerBank() {
        return cardIssuerBank;
    }

    /**
     * Sets the value of the cardIssuerBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardIssuerBank(String value) {
        this.cardIssuerBank = value;
    }

    /**
     * Gets the value of the cardNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * Sets the value of the cardNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNum(String value) {
        this.cardNum = value;
    }

    /**
     * Gets the value of the cardAuthCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardAuthCode() {
        return cardAuthCode;
    }

    /**
     * Sets the value of the cardAuthCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardAuthCode(String value) {
        this.cardAuthCode = value;
    }

    /**
     * Gets the value of the cardAuthInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardAuthInfo() {
        return cardAuthInfo;
    }

    /**
     * Sets the value of the cardAuthInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardAuthInfo(String value) {
        this.cardAuthInfo = value;
    }

    /**
     * Gets the value of the cardAuthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCardAuthDate() {
        return cardAuthDate;
    }

    /**
     * Sets the value of the cardAuthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCardAuthDate(XMLGregorianCalendar value) {
        this.cardAuthDate = value;
    }

    /**
     * Gets the value of the cardRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardRefNum() {
        return cardRefNum;
    }

    /**
     * Sets the value of the cardRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardRefNum(String value) {
        this.cardRefNum = value;
    }

    /**
     * Gets the value of the cardExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCardExpirationDate() {
        return cardExpirationDate;
    }

    /**
     * Sets the value of the cardExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCardExpirationDate(XMLGregorianCalendar value) {
        this.cardExpirationDate = value;
    }

    /**
     * Gets the value of the cardTypeOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardTypeOther() {
        return cardTypeOther;
    }

    /**
     * Sets the value of the cardTypeOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardTypeOther(String value) {
        this.cardTypeOther = value;
    }

    /**
     * Gets the value of the cardHolderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardHolderName() {
        return cardHolderName;
    }

    /**
     * Sets the value of the cardHolderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardHolderName(String value) {
        this.cardHolderName = value;
    }

    /**
     * Gets the value of the cardReportingLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardReportingLevel() {
        return cardReportingLevel;
    }

    /**
     * Sets the value of the cardReportingLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardReportingLevel(String value) {
        this.cardReportingLevel = value;
    }

}
