//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.01 at 02:39:05 PM IST 
//


package com.hp.sales.om.orders;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Discount / special deal information; DiscounType OPG is obsolete; DIS is to be used instead 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountCode" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountID" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountDealID" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountBundleID" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountConditionCode" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountAmount" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountPercent" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountDealPrice" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountDaysDue" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountDueDate" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscounTimeRef" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountVersion" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}DiscountExchangeRate" minOccurs="0"/>
 *         &lt;element name="DiscountDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DiscounType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DiscountBundle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "discountCode",
    "discountID",
    "discountDealID",
    "discountBundleID",
    "discountConditionCode",
    "discountAmount",
    "discountPercent",
    "discountDealPrice",
    "discountDaysDue",
    "discountDueDate",
    "discounTimeRef",
    "discountVersion",
    "discountExchangeRate",
    "discountDescription"
})
@XmlRootElement(name = "Discount")
public class Discount {

    @XmlElement(name = "DiscountCode")
    protected String discountCode;
    @XmlElement(name = "DiscountID")
    protected String discountID;
    @XmlElement(name = "DiscountDealID")
    protected String discountDealID;
    @XmlElement(name = "DiscountBundleID")
    protected String discountBundleID;
    @XmlElement(name = "DiscountConditionCode")
    protected String discountConditionCode;
    @XmlElement(name = "DiscountAmount")
    protected BigDecimal discountAmount;
    @XmlElement(name = "DiscountPercent")
    protected Float discountPercent;
    @XmlElement(name = "DiscountDealPrice")
    protected BigDecimal discountDealPrice;
    @XmlElement(name = "DiscountDaysDue")
    protected Integer discountDaysDue;
    @XmlElement(name = "DiscountDueDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar discountDueDate;
    @XmlElement(name = "DiscounTimeRef")
    protected String discounTimeRef;
    @XmlElement(name = "DiscountVersion")
    protected String discountVersion;
    @XmlElement(name = "DiscountExchangeRate")
    protected BigDecimal discountExchangeRate;
    @XmlElement(name = "DiscountDescription")
    protected String discountDescription;
    @XmlAttribute(name = "DiscounType", required = true)
    protected String discounType;
    @XmlAttribute(name = "DiscountBundle")
    protected String discountBundle;

    /**
     * Gets the value of the discountCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountCode() {
        return discountCode;
    }

    /**
     * Sets the value of the discountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountCode(String value) {
        this.discountCode = value;
    }

    /**
     * Gets the value of the discountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountID() {
        return discountID;
    }

    /**
     * Sets the value of the discountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountID(String value) {
        this.discountID = value;
    }

    /**
     * Gets the value of the discountDealID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountDealID() {
        return discountDealID;
    }

    /**
     * Sets the value of the discountDealID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountDealID(String value) {
        this.discountDealID = value;
    }

    /**
     * Gets the value of the discountBundleID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountBundleID() {
        return discountBundleID;
    }

    /**
     * Sets the value of the discountBundleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountBundleID(String value) {
        this.discountBundleID = value;
    }

    /**
     * Gets the value of the discountConditionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountConditionCode() {
        return discountConditionCode;
    }

    /**
     * Sets the value of the discountConditionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountConditionCode(String value) {
        this.discountConditionCode = value;
    }

    /**
     * Gets the value of the discountAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * Sets the value of the discountAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountAmount(BigDecimal value) {
        this.discountAmount = value;
    }

    /**
     * Gets the value of the discountPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDiscountPercent() {
        return discountPercent;
    }

    /**
     * Sets the value of the discountPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDiscountPercent(Float value) {
        this.discountPercent = value;
    }

    /**
     * Gets the value of the discountDealPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountDealPrice() {
        return discountDealPrice;
    }

    /**
     * Sets the value of the discountDealPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountDealPrice(BigDecimal value) {
        this.discountDealPrice = value;
    }

    /**
     * Gets the value of the discountDaysDue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDiscountDaysDue() {
        return discountDaysDue;
    }

    /**
     * Sets the value of the discountDaysDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDiscountDaysDue(Integer value) {
        this.discountDaysDue = value;
    }

    /**
     * Gets the value of the discountDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDiscountDueDate() {
        return discountDueDate;
    }

    /**
     * Sets the value of the discountDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDiscountDueDate(XMLGregorianCalendar value) {
        this.discountDueDate = value;
    }

    /**
     * Gets the value of the discounTimeRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscounTimeRef() {
        return discounTimeRef;
    }

    /**
     * Sets the value of the discounTimeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscounTimeRef(String value) {
        this.discounTimeRef = value;
    }

    /**
     * Gets the value of the discountVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountVersion() {
        return discountVersion;
    }

    /**
     * Sets the value of the discountVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountVersion(String value) {
        this.discountVersion = value;
    }

    /**
     * Gets the value of the discountExchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountExchangeRate() {
        return discountExchangeRate;
    }

    /**
     * Sets the value of the discountExchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountExchangeRate(BigDecimal value) {
        this.discountExchangeRate = value;
    }

    /**
     * Gets the value of the discountDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountDescription() {
        return discountDescription;
    }

    /**
     * Sets the value of the discountDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountDescription(String value) {
        this.discountDescription = value;
    }

    /**
     * Gets the value of the discounType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscounType() {
        return discounType;
    }

    /**
     * Sets the value of the discounType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscounType(String value) {
        this.discounType = value;
    }

    /**
     * Gets the value of the discountBundle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountBundle() {
        return discountBundle;
    }

    /**
     * Sets the value of the discountBundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountBundle(String value) {
        this.discountBundle = value;
    }

}
