//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.01 at 02:39:05 PM IST 
//


package com.hp.sales.om.orders;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}messageID"/>
 *         &lt;element name="SenderMessageID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ParentFileID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CorrelationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TargetSpecificMessageID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}SystemMessageID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}sent"/>
 *         &lt;element ref="{http://hp.com/sales/om/orders/}subject" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageID",
    "senderMessageID",
    "parentFileID",
    "correlationID",
    "targetSpecificMessageID",
    "systemMessageID",
    "sent",
    "subject"
})
@XmlRootElement(name = "message")
public class Message {

    @XmlElement(required = true)
    protected String messageID;
    @XmlElement(name = "SenderMessageID")
    protected String senderMessageID;
    @XmlElement(name = "ParentFileID")
    protected String parentFileID;
    @XmlElement(name = "CorrelationID")
    protected String correlationID;
    @XmlElement(name = "TargetSpecificMessageID")
    protected String targetSpecificMessageID;
    @XmlElement(name = "SystemMessageID")
    protected List<SystemMessageID> systemMessageID;
    @XmlElement(required = true)
    protected String sent;
    protected String subject;

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the senderMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderMessageID() {
        return senderMessageID;
    }

    /**
     * Sets the value of the senderMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderMessageID(String value) {
        this.senderMessageID = value;
    }

    /**
     * Gets the value of the parentFileID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFileID() {
        return parentFileID;
    }

    /**
     * Sets the value of the parentFileID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFileID(String value) {
        this.parentFileID = value;
    }

    /**
     * Gets the value of the correlationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationID() {
        return correlationID;
    }

    /**
     * Sets the value of the correlationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationID(String value) {
        this.correlationID = value;
    }

    /**
     * Gets the value of the targetSpecificMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetSpecificMessageID() {
        return targetSpecificMessageID;
    }

    /**
     * Sets the value of the targetSpecificMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetSpecificMessageID(String value) {
        this.targetSpecificMessageID = value;
    }

    /**
     * All known message identifiers with system name to enable cross referencing and end to end tracking Gets the value of the systemMessageID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemMessageID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemMessageID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemMessageID }
     * 
     * 
     */
    public List<SystemMessageID> getSystemMessageID() {
        if (systemMessageID == null) {
            systemMessageID = new ArrayList<SystemMessageID>();
        }
        return this.systemMessageID;
    }

    /**
     * Timestamp in universal coordinated time format is a key metric end to end for process flow optimization
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSent() {
        return sent;
    }

    /**
     * Sets the value of the sent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSent(String value) {
        this.sent = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

}
