//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.01 at 02:39:05 PM IST 
//


package com.hp.sales.om.orders;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hp.sales.om.orders package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CardType_QNAME = new QName("http://hp.com/sales/om/orders/", "CardType");
    private final static QName _ItemNumber_QNAME = new QName("http://hp.com/sales/om/orders/", "ItemNumber");
    private final static QName _Format_QNAME = new QName("http://hp.com/sales/om/orders/", "Format");
    private final static QName _CardExpirationDate_QNAME = new QName("http://hp.com/sales/om/orders/", "CardExpirationDate");
    private final static QName _DateDesc_QNAME = new QName("http://hp.com/sales/om/orders/", "DateDesc");
    private final static QName _TotalNumLines_QNAME = new QName("http://hp.com/sales/om/orders/", "TotalNumLines");
    private final static QName _ISOCurrency_QNAME = new QName("http://hp.com/sales/om/orders/", "ISOCurrency");
    private final static QName _ContactFax_QNAME = new QName("http://hp.com/sales/om/orders/", "ContactFax");
    private final static QName _FormatVersion_QNAME = new QName("http://hp.com/sales/om/orders/", "FormatVersion");
    private final static QName _IDCode_QNAME = new QName("http://hp.com/sales/om/orders/", "IDCode");
    private final static QName _ContextID_QNAME = new QName("http://hp.com/sales/om/orders/", "ContextID");
    private final static QName _ContactDivision_QNAME = new QName("http://hp.com/sales/om/orders/", "ContactDivision");
    private final static QName _HoldStatus_QNAME = new QName("http://hp.com/sales/om/orders/", "HoldStatus");
    private final static QName _ExchangeRate_QNAME = new QName("http://hp.com/sales/om/orders/", "ExchangeRate");
    private final static QName _CardAuthCode_QNAME = new QName("http://hp.com/sales/om/orders/", "CardAuthCode");
    private final static QName _POBox_QNAME = new QName("http://hp.com/sales/om/orders/", "POBox");
    private final static QName _InstructValue_QNAME = new QName("http://hp.com/sales/om/orders/", "InstructValue");
    private final static QName _Time_QNAME = new QName("http://hp.com/sales/om/orders/", "Time");
    private final static QName _Description_QNAME = new QName("http://hp.com/sales/om/orders/", "description");
    private final static QName _ContactPhoneMobile_QNAME = new QName("http://hp.com/sales/om/orders/", "ContactPhoneMobile");
    private final static QName _ProductDescription_QNAME = new QName("http://hp.com/sales/om/orders/", "ProductDescription");
    private final static QName _ContactEmail_QNAME = new QName("http://hp.com/sales/om/orders/", "ContactEmail");
    private final static QName _DiscountDaysDue_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountDaysDue");
    private final static QName _Process_QNAME = new QName("http://hp.com/sales/om/orders/", "process");
    private final static QName _DiscountID_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountID");
    private final static QName _Date_QNAME = new QName("http://hp.com/sales/om/orders/", "Date");
    private final static QName _TotalAmount_QNAME = new QName("http://hp.com/sales/om/orders/", "TotalAmount");
    private final static QName _ContactID_QNAME = new QName("http://hp.com/sales/om/orders/", "ContactID");
    private final static QName _DiscountExchangeRate_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountExchangeRate");
    private final static QName _DiscountDealID_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountDealID");
    private final static QName _Carrier_QNAME = new QName("http://hp.com/sales/om/orders/", "Carrier");
    private final static QName _TransportInstructions_QNAME = new QName("http://hp.com/sales/om/orders/", "TransportInstructions");
    private final static QName _DocumentDesc_QNAME = new QName("http://hp.com/sales/om/orders/", "DocumentDesc");
    private final static QName _Subject_QNAME = new QName("http://hp.com/sales/om/orders/", "subject");
    private final static QName _ZIPCode_QNAME = new QName("http://hp.com/sales/om/orders/", "ZIPCode");
    private final static QName _ProductName_QNAME = new QName("http://hp.com/sales/om/orders/", "ProductName");
    private final static QName _CarrierOther_QNAME = new QName("http://hp.com/sales/om/orders/", "CarrierOther");
    private final static QName _Company_QNAME = new QName("http://hp.com/sales/om/orders/", "Company");
    private final static QName _CardHolderName_QNAME = new QName("http://hp.com/sales/om/orders/", "CardHolderName");
    private final static QName _State_QNAME = new QName("http://hp.com/sales/om/orders/", "State");
    private final static QName _DiscountConditionCode_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountConditionCode");
    private final static QName _PriceDescription_QNAME = new QName("http://hp.com/sales/om/orders/", "PriceDescription");
    private final static QName _BusinessID_QNAME = new QName("http://hp.com/sales/om/orders/", "BusinessID");
    private final static QName _Option_QNAME = new QName("http://hp.com/sales/om/orders/", "Option");
    private final static QName _DateTimeUTC_QNAME = new QName("http://hp.com/sales/om/orders/", "DateTimeUTC");
    private final static QName _InstructCode_QNAME = new QName("http://hp.com/sales/om/orders/", "InstructCode");
    private final static QName _Name_QNAME = new QName("http://hp.com/sales/om/orders/", "name");
    private final static QName _PriceAmount_QNAME = new QName("http://hp.com/sales/om/orders/", "PriceAmount");
    private final static QName _ReferenceID_QNAME = new QName("http://hp.com/sales/om/orders/", "referenceID");
    private final static QName _Sent_QNAME = new QName("http://hp.com/sales/om/orders/", "sent");
    private final static QName _City_QNAME = new QName("http://hp.com/sales/om/orders/", "City");
    private final static QName _ProductNumber_QNAME = new QName("http://hp.com/sales/om/orders/", "ProductNumber");
    private final static QName _DocumentID_QNAME = new QName("http://hp.com/sales/om/orders/", "DocumentID");
    private final static QName _ContactPhoneHome_QNAME = new QName("http://hp.com/sales/om/orders/", "ContactPhoneHome");
    private final static QName _DiscountDueDate_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountDueDate");
    private final static QName _TransportMeanOther_QNAME = new QName("http://hp.com/sales/om/orders/", "TransportMeanOther");
    private final static QName _ContactPhone_QNAME = new QName("http://hp.com/sales/om/orders/", "ContactPhone");
    private final static QName _PaymentMean_QNAME = new QName("http://hp.com/sales/om/orders/", "PaymentMean");
    private final static QName _Division_QNAME = new QName("http://hp.com/sales/om/orders/", "Division");
    private final static QName _CommodityCode_QNAME = new QName("http://hp.com/sales/om/orders/", "CommodityCode");
    private final static QName _OptionDescription_QNAME = new QName("http://hp.com/sales/om/orders/", "OptionDescription");
    private final static QName _OrderQuantity_QNAME = new QName("http://hp.com/sales/om/orders/", "OrderQuantity");
    private final static QName _LineNumber_QNAME = new QName("http://hp.com/sales/om/orders/", "LineNumber");
    private final static QName _PriceDescriptor_QNAME = new QName("http://hp.com/sales/om/orders/", "PriceDescriptor");
    private final static QName _CardRefNum_QNAME = new QName("http://hp.com/sales/om/orders/", "CardRefNum");
    private final static QName _DiscountBundleID_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountBundleID");
    private final static QName _MessageID_QNAME = new QName("http://hp.com/sales/om/orders/", "messageID");
    private final static QName _Currency2_QNAME = new QName("http://hp.com/sales/om/orders/", "currency2");
    private final static QName _TaxLocation_QNAME = new QName("http://hp.com/sales/om/orders/", "TaxLocation");
    private final static QName _HoldCode_QNAME = new QName("http://hp.com/sales/om/orders/", "HoldCode");
    private final static QName _TaxableAmount_QNAME = new QName("http://hp.com/sales/om/orders/", "TaxableAmount");
    private final static QName _DescriptionUOM_QNAME = new QName("http://hp.com/sales/om/orders/", "DescriptionUOM");
    private final static QName _Address_QNAME = new QName("http://hp.com/sales/om/orders/", "address");
    private final static QName _TaxPercent_QNAME = new QName("http://hp.com/sales/om/orders/", "TaxPercent");
    private final static QName _POBoxZIP_QNAME = new QName("http://hp.com/sales/om/orders/", "POBoxZIP");
    private final static QName _DiscountCode_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountCode");
    private final static QName _ISOCountryCode_QNAME = new QName("http://hp.com/sales/om/orders/", "ISOCountryCode");
    private final static QName _CostLocation_QNAME = new QName("http://hp.com/sales/om/orders/", "CostLocation");
    private final static QName _TaxAmount_QNAME = new QName("http://hp.com/sales/om/orders/", "TaxAmount");
    private final static QName _DiscountVersion_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountVersion");
    private final static QName _ProductLine_QNAME = new QName("http://hp.com/sales/om/orders/", "ProductLine");
    private final static QName _DiscountPercent_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountPercent");
    private final static QName _TransportModeOther_QNAME = new QName("http://hp.com/sales/om/orders/", "TransportModeOther");
    private final static QName _TransportMean_QNAME = new QName("http://hp.com/sales/om/orders/", "TransportMean");
    private final static QName _Street_QNAME = new QName("http://hp.com/sales/om/orders/", "Street");
    private final static QName _CardTypeOther_QNAME = new QName("http://hp.com/sales/om/orders/", "CardTypeOther");
    private final static QName _PaymenTermOther_QNAME = new QName("http://hp.com/sales/om/orders/", "PaymenTermOther");
    private final static QName _InstructCodesc_QNAME = new QName("http://hp.com/sales/om/orders/", "InstructCodesc");
    private final static QName _CardNum_QNAME = new QName("http://hp.com/sales/om/orders/", "CardNum");
    private final static QName _TransportContractNumber_QNAME = new QName("http://hp.com/sales/om/orders/", "TransportContractNumber");
    private final static QName _DiscounTimeRef_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscounTimeRef");
    private final static QName _IDDesc_QNAME = new QName("http://hp.com/sales/om/orders/", "IDDesc");
    private final static QName _PaymenTerm_QNAME = new QName("http://hp.com/sales/om/orders/", "PaymenTerm");
    private final static QName _BusinessDesc_QNAME = new QName("http://hp.com/sales/om/orders/", "BusinessDesc");
    private final static QName _TransportMode_QNAME = new QName("http://hp.com/sales/om/orders/", "TransportMode");
    private final static QName _DiscountDealPrice_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountDealPrice");
    private final static QName _DiscountAmount_QNAME = new QName("http://hp.com/sales/om/orders/", "DiscountAmount");
    private final static QName _FormatVariant_QNAME = new QName("http://hp.com/sales/om/orders/", "FormatVariant");
    private final static QName _Handle_QNAME = new QName("http://hp.com/sales/om/orders/", "handle");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hp.sales.om.orders
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BuyerID }
     * 
     */
    public BuyerID createBuyerID() {
        return new BuyerID();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link ProductInformation }
     * 
     */
    public ProductInformation createProductInformation() {
        return new ProductInformation();
    }

    /**
     * Create an instance of {@link ProductOption }
     * 
     */
    public ProductOption createProductOption() {
        return new ProductOption();
    }

    /**
     * Create an instance of {@link ProductAttribute }
     * 
     */
    public ProductAttribute createProductAttribute() {
        return new ProductAttribute();
    }

    /**
     * Create an instance of {@link Currency }
     * 
     */
    public Currency createCurrency() {
        return new Currency();
    }

    /**
     * Create an instance of {@link Quantity }
     * 
     */
    public Quantity createQuantity() {
        return new Quantity();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link Tax }
     * 
     */
    public Tax createTax() {
        return new Tax();
    }

    /**
     * Create an instance of {@link ChargeOrDiscount }
     * 
     */
    public ChargeOrDiscount createChargeOrDiscount() {
        return new ChargeOrDiscount();
    }

    /**
     * Create an instance of {@link MonetaryAmount }
     * 
     */
    public MonetaryAmount createMonetaryAmount() {
        return new MonetaryAmount();
    }

    /**
     * Create an instance of {@link Instructions }
     * 
     */
    public Instructions createInstructions() {
        return new Instructions();
    }

    /**
     * Create an instance of {@link DocumentReference }
     * 
     */
    public DocumentReference createDocumentReference() {
        return new DocumentReference();
    }

    /**
     * Create an instance of {@link CustomerReference }
     * 
     */
    public CustomerReference createCustomerReference() {
        return new CustomerReference();
    }

    /**
     * Create an instance of {@link BuyerID.SystemIDCode }
     * 
     */
    public BuyerID.SystemIDCode createBuyerIDSystemIDCode() {
        return new BuyerID.SystemIDCode();
    }

    /**
     * Create an instance of {@link ContactInfo }
     * 
     */
    public ContactInfo createContactInfo() {
        return new ContactInfo();
    }

    /**
     * Create an instance of {@link ContactName }
     * 
     */
    public ContactName createContactName() {
        return new ContactName();
    }

    /**
     * Create an instance of {@link Discount }
     * 
     */
    public Discount createDiscount() {
        return new Discount();
    }

    /**
     * Create an instance of {@link DateInfo }
     * 
     */
    public DateInfo createDateInfo() {
        return new DateInfo();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link HoldGroupLocation }
     * 
     */
    public HoldGroupLocation createHoldGroupLocation() {
        return new HoldGroupLocation();
    }

    /**
     * Create an instance of {@link BundleItem }
     * 
     */
    public BundleItem createBundleItem() {
        return new BundleItem();
    }

    /**
     * Create an instance of {@link Transport }
     * 
     */
    public Transport createTransport() {
        return new Transport();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link ServiceHeader }
     * 
     */
    public ServiceHeader createServiceHeader() {
        return new ServiceHeader();
    }

    /**
     * Create an instance of {@link HoldConfiguration }
     * 
     */
    public HoldConfiguration createHoldConfiguration() {
        return new HoldConfiguration();
    }

    /**
     * Create an instance of {@link HoldParameter }
     * 
     */
    public HoldParameter createHoldParameter() {
        return new HoldParameter();
    }

    /**
     * Create an instance of {@link OrderItem }
     * 
     */
    public OrderItem createOrderItem() {
        return new OrderItem();
    }

    /**
     * Create an instance of {@link PurchaseOrder }
     * 
     */
    public PurchaseOrder createPurchaseOrder() {
        return new PurchaseOrder();
    }

    /**
     * Create an instance of {@link OrderHeader }
     * 
     */
    public OrderHeader createOrderHeader() {
        return new OrderHeader();
    }

    /**
     * Create an instance of {@link Hold }
     * 
     */
    public Hold createHold() {
        return new Hold();
    }

    /**
     * Create an instance of {@link HoldLocation }
     * 
     */
    public HoldLocation createHoldLocation() {
        return new HoldLocation();
    }

    /**
     * Create an instance of {@link AuditLog }
     * 
     */
    public AuditLog createAuditLog() {
        return new AuditLog();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link CardInfo }
     * 
     */
    public CardInfo createCardInfo() {
        return new CardInfo();
    }

    /**
     * Create an instance of {@link OrderSummary }
     * 
     */
    public OrderSummary createOrderSummary() {
        return new OrderSummary();
    }

    /**
     * Create an instance of {@link To }
     * 
     */
    public To createTo() {
        return new To();
    }

    /**
     * Create an instance of {@link DeliveryDate }
     * 
     */
    public DeliveryDate createDeliveryDate() {
        return new DeliveryDate();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link From }
     * 
     */
    public From createFrom() {
        return new From();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Delivery }
     * 
     */
    public Delivery createDelivery() {
        return new Delivery();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link SystemMessageID }
     * 
     */
    public SystemMessageID createSystemMessageID() {
        return new SystemMessageID();
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link Biztalk1 }
     * 
     */
    public Biztalk1 createBiztalk1() {
        return new Biztalk1();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "CardType")
    public JAXBElement<String> createCardType(String value) {
        return new JAXBElement<String>(_CardType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ItemNumber")
    public JAXBElement<String> createItemNumber(String value) {
        return new JAXBElement<String>(_ItemNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "Format")
    public JAXBElement<String> createFormat(String value) {
        return new JAXBElement<String>(_Format_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "CardExpirationDate")
    public JAXBElement<XMLGregorianCalendar> createCardExpirationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CardExpirationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DateDesc")
    public JAXBElement<String> createDateDesc(String value) {
        return new JAXBElement<String>(_DateDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TotalNumLines")
    public JAXBElement<Integer> createTotalNumLines(Integer value) {
        return new JAXBElement<Integer>(_TotalNumLines_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ISOCurrency")
    public JAXBElement<String> createISOCurrency(String value) {
        return new JAXBElement<String>(_ISOCurrency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ContactFax")
    public JAXBElement<String> createContactFax(String value) {
        return new JAXBElement<String>(_ContactFax_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "FormatVersion")
    public JAXBElement<String> createFormatVersion(String value) {
        return new JAXBElement<String>(_FormatVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "IDCode")
    public JAXBElement<String> createIDCode(String value) {
        return new JAXBElement<String>(_IDCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ContextID")
    public JAXBElement<String> createContextID(String value) {
        return new JAXBElement<String>(_ContextID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ContactDivision")
    public JAXBElement<String> createContactDivision(String value) {
        return new JAXBElement<String>(_ContactDivision_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "HoldStatus")
    public JAXBElement<String> createHoldStatus(String value) {
        return new JAXBElement<String>(_HoldStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ExchangeRate")
    public JAXBElement<Float> createExchangeRate(Float value) {
        return new JAXBElement<Float>(_ExchangeRate_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "CardAuthCode")
    public JAXBElement<String> createCardAuthCode(String value) {
        return new JAXBElement<String>(_CardAuthCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "POBox")
    public JAXBElement<String> createPOBox(String value) {
        return new JAXBElement<String>(_POBox_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "InstructValue")
    public JAXBElement<String> createInstructValue(String value) {
        return new JAXBElement<String>(_InstructValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "Time")
    public JAXBElement<XMLGregorianCalendar> createTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Time_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ContactPhoneMobile")
    public JAXBElement<String> createContactPhoneMobile(String value) {
        return new JAXBElement<String>(_ContactPhoneMobile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ProductDescription")
    public JAXBElement<String> createProductDescription(String value) {
        return new JAXBElement<String>(_ProductDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ContactEmail")
    public JAXBElement<String> createContactEmail(String value) {
        return new JAXBElement<String>(_ContactEmail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountDaysDue")
    public JAXBElement<Integer> createDiscountDaysDue(Integer value) {
        return new JAXBElement<Integer>(_DiscountDaysDue_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "process")
    public JAXBElement<String> createProcess(String value) {
        return new JAXBElement<String>(_Process_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountID")
    public JAXBElement<String> createDiscountID(String value) {
        return new JAXBElement<String>(_DiscountID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "Date")
    public JAXBElement<XMLGregorianCalendar> createDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Date_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TotalAmount")
    public JAXBElement<BigDecimal> createTotalAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TotalAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ContactID")
    public JAXBElement<String> createContactID(String value) {
        return new JAXBElement<String>(_ContactID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountExchangeRate")
    public JAXBElement<BigDecimal> createDiscountExchangeRate(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DiscountExchangeRate_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountDealID")
    public JAXBElement<String> createDiscountDealID(String value) {
        return new JAXBElement<String>(_DiscountDealID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "Carrier")
    public JAXBElement<String> createCarrier(String value) {
        return new JAXBElement<String>(_Carrier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TransportInstructions")
    public JAXBElement<String> createTransportInstructions(String value) {
        return new JAXBElement<String>(_TransportInstructions_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DocumentDesc")
    public JAXBElement<String> createDocumentDesc(String value) {
        return new JAXBElement<String>(_DocumentDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "subject")
    public JAXBElement<String> createSubject(String value) {
        return new JAXBElement<String>(_Subject_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ZIPCode")
    public JAXBElement<String> createZIPCode(String value) {
        return new JAXBElement<String>(_ZIPCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ProductName")
    public JAXBElement<String> createProductName(String value) {
        return new JAXBElement<String>(_ProductName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "CarrierOther")
    public JAXBElement<String> createCarrierOther(String value) {
        return new JAXBElement<String>(_CarrierOther_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "Company")
    public JAXBElement<String> createCompany(String value) {
        return new JAXBElement<String>(_Company_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "CardHolderName")
    public JAXBElement<String> createCardHolderName(String value) {
        return new JAXBElement<String>(_CardHolderName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "State")
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountConditionCode")
    public JAXBElement<String> createDiscountConditionCode(String value) {
        return new JAXBElement<String>(_DiscountConditionCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "PriceDescription")
    public JAXBElement<String> createPriceDescription(String value) {
        return new JAXBElement<String>(_PriceDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "BusinessID")
    public JAXBElement<String> createBusinessID(String value) {
        return new JAXBElement<String>(_BusinessID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "Option")
    public JAXBElement<String> createOption(String value) {
        return new JAXBElement<String>(_Option_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DateTimeUTC")
    public JAXBElement<XMLGregorianCalendar> createDateTimeUTC(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTimeUTC_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "InstructCode")
    public JAXBElement<String> createInstructCode(String value) {
        return new JAXBElement<String>(_InstructCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "PriceAmount")
    public JAXBElement<BigDecimal> createPriceAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PriceAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "referenceID")
    public JAXBElement<String> createReferenceID(String value) {
        return new JAXBElement<String>(_ReferenceID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "sent")
    public JAXBElement<String> createSent(String value) {
        return new JAXBElement<String>(_Sent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "City")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ProductNumber")
    public JAXBElement<String> createProductNumber(String value) {
        return new JAXBElement<String>(_ProductNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DocumentID")
    public JAXBElement<String> createDocumentID(String value) {
        return new JAXBElement<String>(_DocumentID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ContactPhoneHome")
    public JAXBElement<String> createContactPhoneHome(String value) {
        return new JAXBElement<String>(_ContactPhoneHome_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountDueDate")
    public JAXBElement<XMLGregorianCalendar> createDiscountDueDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DiscountDueDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TransportMeanOther")
    public JAXBElement<String> createTransportMeanOther(String value) {
        return new JAXBElement<String>(_TransportMeanOther_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ContactPhone")
    public JAXBElement<String> createContactPhone(String value) {
        return new JAXBElement<String>(_ContactPhone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "PaymentMean")
    public JAXBElement<String> createPaymentMean(String value) {
        return new JAXBElement<String>(_PaymentMean_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "Division")
    public JAXBElement<String> createDivision(String value) {
        return new JAXBElement<String>(_Division_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "CommodityCode")
    public JAXBElement<String> createCommodityCode(String value) {
        return new JAXBElement<String>(_CommodityCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "OptionDescription")
    public JAXBElement<String> createOptionDescription(String value) {
        return new JAXBElement<String>(_OptionDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "OrderQuantity")
    public JAXBElement<Integer> createOrderQuantity(Integer value) {
        return new JAXBElement<Integer>(_OrderQuantity_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "LineNumber")
    public JAXBElement<Integer> createLineNumber(Integer value) {
        return new JAXBElement<Integer>(_LineNumber_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "PriceDescriptor")
    public JAXBElement<String> createPriceDescriptor(String value) {
        return new JAXBElement<String>(_PriceDescriptor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "CardRefNum")
    public JAXBElement<String> createCardRefNum(String value) {
        return new JAXBElement<String>(_CardRefNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountBundleID")
    public JAXBElement<String> createDiscountBundleID(String value) {
        return new JAXBElement<String>(_DiscountBundleID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "messageID")
    public JAXBElement<String> createMessageID(String value) {
        return new JAXBElement<String>(_MessageID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "currency2")
    public JAXBElement<String> createCurrency2(String value) {
        return new JAXBElement<String>(_Currency2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TaxLocation")
    public JAXBElement<String> createTaxLocation(String value) {
        return new JAXBElement<String>(_TaxLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "HoldCode")
    public JAXBElement<String> createHoldCode(String value) {
        return new JAXBElement<String>(_HoldCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TaxableAmount")
    public JAXBElement<BigDecimal> createTaxableAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TaxableAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DescriptionUOM")
    public JAXBElement<String> createDescriptionUOM(String value) {
        return new JAXBElement<String>(_DescriptionUOM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "address")
    public JAXBElement<String> createAddress(String value) {
        return new JAXBElement<String>(_Address_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TaxPercent")
    public JAXBElement<Float> createTaxPercent(Float value) {
        return new JAXBElement<Float>(_TaxPercent_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "POBoxZIP")
    public JAXBElement<String> createPOBoxZIP(String value) {
        return new JAXBElement<String>(_POBoxZIP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountCode")
    public JAXBElement<String> createDiscountCode(String value) {
        return new JAXBElement<String>(_DiscountCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ISOCountryCode")
    public JAXBElement<String> createISOCountryCode(String value) {
        return new JAXBElement<String>(_ISOCountryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "CostLocation")
    public JAXBElement<String> createCostLocation(String value) {
        return new JAXBElement<String>(_CostLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TaxAmount")
    public JAXBElement<BigDecimal> createTaxAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TaxAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountVersion")
    public JAXBElement<String> createDiscountVersion(String value) {
        return new JAXBElement<String>(_DiscountVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "ProductLine")
    public JAXBElement<String> createProductLine(String value) {
        return new JAXBElement<String>(_ProductLine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountPercent")
    public JAXBElement<Float> createDiscountPercent(Float value) {
        return new JAXBElement<Float>(_DiscountPercent_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TransportModeOther")
    public JAXBElement<String> createTransportModeOther(String value) {
        return new JAXBElement<String>(_TransportModeOther_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TransportMean")
    public JAXBElement<String> createTransportMean(String value) {
        return new JAXBElement<String>(_TransportMean_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "Street")
    public JAXBElement<String> createStreet(String value) {
        return new JAXBElement<String>(_Street_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "CardTypeOther")
    public JAXBElement<String> createCardTypeOther(String value) {
        return new JAXBElement<String>(_CardTypeOther_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "PaymenTermOther")
    public JAXBElement<String> createPaymenTermOther(String value) {
        return new JAXBElement<String>(_PaymenTermOther_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "InstructCodesc")
    public JAXBElement<String> createInstructCodesc(String value) {
        return new JAXBElement<String>(_InstructCodesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "CardNum")
    public JAXBElement<String> createCardNum(String value) {
        return new JAXBElement<String>(_CardNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TransportContractNumber")
    public JAXBElement<String> createTransportContractNumber(String value) {
        return new JAXBElement<String>(_TransportContractNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscounTimeRef")
    public JAXBElement<String> createDiscounTimeRef(String value) {
        return new JAXBElement<String>(_DiscounTimeRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "IDDesc")
    public JAXBElement<String> createIDDesc(String value) {
        return new JAXBElement<String>(_IDDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "PaymenTerm")
    public JAXBElement<String> createPaymenTerm(String value) {
        return new JAXBElement<String>(_PaymenTerm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "BusinessDesc")
    public JAXBElement<String> createBusinessDesc(String value) {
        return new JAXBElement<String>(_BusinessDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "TransportMode")
    public JAXBElement<String> createTransportMode(String value) {
        return new JAXBElement<String>(_TransportMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountDealPrice")
    public JAXBElement<BigDecimal> createDiscountDealPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DiscountDealPrice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "DiscountAmount")
    public JAXBElement<BigDecimal> createDiscountAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DiscountAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "FormatVariant")
    public JAXBElement<String> createFormatVariant(String value) {
        return new JAXBElement<String>(_FormatVariant_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hp.com/sales/om/orders/", name = "handle")
    public JAXBElement<String> createHandle(String value) {
        return new JAXBElement<String>(_Handle_QNAME, String.class, null, value);
    }

}
